package com.Staff.Entities;

import jakarta.persistence.*;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.security.SecureRandom;
import java.time.LocalDate;
import java.util.*;

@Getter
@Setter
@Data
@NoArgsConstructor
@Entity
@Table(name = "staff")
public class Staff {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String gender;
    private Long mobile;
    private String dateOfJoining;
    private String address;
    private LocalDate dob;
    private String designation;
    private String email;
    private String staffId;
    private String department;
    private String approver;

    @OneToMany(mappedBy = "staff")
    private List<StaffImage> images;

    @ElementCollection
    @CollectionTable(name = "staff_subjects", joinColumns = @JoinColumn(name = "staff_id"))
    @Column(name = "subject")
    private List<String> subjects = new ArrayList<>();

    @Column(nullable = false)
    private String password;

    public Staff(String name, String gender, Long mobile, String dateOfJoining, String address,
                 LocalDate dob, String designation, String email, String staffId, String department, String approver) {
        this.name = name;
        this.gender = gender;
        this.mobile = mobile;
        this.dateOfJoining = dateOfJoining;
        this.address = address;
        this.dob = dob;
        this.designation = designation;
        this.email = email;
        this.staffId = staffId;
        this.department = department;
        this.approver = approver;
        generateRandomPassword(); // Generate password during object creation
    }

    @PrePersist
    protected void onCreate() {
        if (this.password == null || this.password.isEmpty()) {
            generateRandomPassword();
        }
    }

    private void generateRandomPassword() {
        int length = 10; // Password length set to 10 characters
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@#$%&*";
        SecureRandom random = new SecureRandom();
        StringBuilder generatedPassword = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            generatedPassword.append(chars.charAt(random.nextInt(chars.length())));
        }
        this.password = generatedPassword.toString();
    }

    // Getter method to access the autogenerated password
    public String getAutogeneratedPassword() {
        return password;
    }
}
